immobilier/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from .views import  home
from accounts.views import  LoginView, RegisterPromoreurView,RegisterPromoreur
from django.contrib.auth.views import LogoutView
from contacts.views import  SendContactForm

from offres.views import  CreateFormView,loadBien

urlpatterns = [
    path('', home, name="home"),
    path('admin/', admin.site.urls),

    #Account
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('ajouterutilisateur/',RegisterPromoreurView.as_view(), name="ajouter-utilisateur"),

    #Contact
    path('contact/', SendContactForm.as_view(), name="contact"),
    #Marque
    path('marques/', include('marques.urls',namespace="marque")),

    #Promoteurs
    path('promoteur/', include('promoteurs.urls', namespace="promoteurs")),

    #Project
    path('projects/', include('projets.urls', namespace="projects")),

    #Offres
    path('offre/ajouter/', CreateFormView.as_view(), name="ajouter-offre"),
    path('ajax/loads-bien',loadBien , name="loads-biens")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marques/urls.py
from django.urls import  path
from .views import  CreateMarqueView,ListMarque
app_name = 'marque'
urlpatterns = [
    path('',ListMarque.as_view(), name="list-marques"),
    path('ajouter',CreateMarqueView.as_view(), name="ajouter-marque"),
]

projets/urls.py
from django.urls import  path
from .views import  CreateProjectVie

app_name = 'projects'

urlpatterns = [
    path('ajouterproject', CreateProjectVie.as_view(), name="ajouter")
]

templates/layouts/footer.html
	<footer class="dark-footer skin-dark-footer">
        <div>
            <div class="container">
                <div class="row">
                    
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h4 class="widget-title">About Workio</h4>
                            <p>Themez Hub is a team of young professionals that has been successfully creating Creative Website templates already for several years.</p>
                            <a href="#" class="other-store-link">
                                <div class="other-store-app">
                                    <div class="os-app-icon">
                                        <i class="ti-android"></i>
                                    </div>
                                    <div class="os-app-caps">
                                        Google Store
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>		
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h4 class="widget-title">Useful links</h4>
                            <ul class="footer-menu">
                                <li><a href="about-us.html">About Us</a></li>
                                <li><a href="faq.html">FAQs Page</a></li>
                                <li><a href="checkout.html">Checkout</a></li>
                                <li><a href="about-us.html">About Us</a></li>
                                <li><a href="about-us.html">About Us</a></li>
                            </ul>
                        </div>
                    </div>
                            
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h4 class="widget-title">Get in Touch</h4>
                            <div class="fw-address-wrap">
                                <div class="fw fw-location">
                                    7744 North Park, New York
                                </div>
                                <div class="fw fw-mail">
                                    support@drizvato77.com
                                </div>
                                <div class="fw fw-call">
                                    +91 254 584 7584
                                </div>
                                <div class="fw fw-skype">
                                    drizvato77
                                </div>
                                <div class="fw fw-web">
                                    www.Themez Hub.com
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h4 class="widget-title">Follow Us</h4>
                            <p>Follow & Subscribe your email to get new business tips.</p>
                            <ul class="footer-bottom-social">
                                <li><a href="#"><i class="ti-facebook"></i></a></li>
                                <li><a href="#"><i class="ti-twitter"></i></a></li>
                                <li><a href="#"><i class="ti-instagram"></i></a></li>
                                <li><a href="#"><i class="ti-linkedin"></i></a></li>
                            </ul>
                            
                            <form class="f-newsletter mt-4">
                                <input type="email" class="form-control sigmup-me" placeholder="Your Email Address" required="required">
                                <button type="submit" class="btn"><i class="ti-arrow-right"></i></button>
                            </form>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        
        <div class="footer-bottom">
            <div class="container">
                <div class="row align-items-center">
                    
                    <div class="col-lg-12 col-md-12 text-center">
                        <p class="mb-0">© 2019 Rikada. Designd By <a href="https://themezhub.com">Themez Hub</a> All Rights Reserved</p>
                    </div>
                    
                </div>
            </div>
        </div>
    </footer>

    
{% include 'layouts/javascipt.html' %}

templates/layouts/javascipt.html
{% load static %}
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/rangeslider.js' %}"></script>
<script src="{% static 'assets/js/select2.min.js' %}"></script>
<script src="{% static 'assets/js/aos.js' %}"></script>
<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'assets/js/slick.js' %}"></script>
<script src="{% static 'assets/js/slider-bg.js' %}"></script>
<script src="{% static 'assets/js/lightbox.js' %}"></script> 
<script src="{% static 'assets/js/imagesloaded.js' %}"></script>
<script src="{% static 'assets/js/isotope.min.js' %}"></script>
<script src="{% static 'assets/js/coreNavigation.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>

<!-- Map -->
<!-- <script src="http://maps.google.com/maps/api/js?key="></script> -->
{% comment %} <script src="{% static 'assets/js/map_infobox.js' %}"></script> {% endcomment %}
<script src="{% static 'assets/js/markerclusterer.js' %}"></script> 
{% comment %} <script src="{% static 'assets/js/map.js' %}"></script> {% endcomment %}

templates/layouts/navbar.html
{% load static %}
<div class="header header-light nav-left-side">
    <nav class="headnavbar">
        <div class="nav-header">
            <a href="{% url 'home' %}" class="brand"><img src="{% static 'assets/img/logo2.png' %}" alt="" /></a>
            <button class="toggle-bar"><span class="ti-align-justify"></span></button>	
        </div>								
        <ul class="menu">
        
            <li class="dropdown">
                <a class="active" href="JavaScript:Void(0);">Acceuil</a>
              
            </li>
            
            <li class="dropdown">
                <a href="">Action</a>
                <ul class="dropdown-menu">
                    <li class="">
                        <a href="{% url 'ajouter-utilisateur' %}">Ajouter Utilisateur</a>
                                                   
                    </li>
                    <li class="">
                        <a href="{% url 'marque:ajouter-marque' %}">Ajouter Marque</a>
                                                   
                    </li>
                    <li class="">
                        <a href="{% url 'promoteurs:ajouter' %}">Ajouter promoteur</a>
                                                   
                    </li>
                    <li class="dropdown">
                        <a href="JavaScript:Void(0);"> Ajouter Projet</a>
                                                     
                    </li>
                    <li class="dropdown">
                        <a href="JavaScript:Void(0);">With Map Layouts</a>
                        <ul class="dropdown-menu">
                            <li><a href="list-layout-with-map.html">List With Map</a></li>                                    
                            <li><a href="grid-layout-with-map.html">Grid With Map</a></li>                                    
                            <li><a href="classical-layout-with-map.html">Classical With Map</a></li>                                    
                            <li><a href="half-map.html">Half Map Search</a></li>   
                        </ul>                                 
                    </li>
                </ul>
            </li>
            
            <li class="dropdown">
                <a href="JavaScript:Void(0);">Offres</a>
                <ul class="dropdown-menu">
                    <li class="dropdown">
                        <a href="JavaScript:Void(0);">Single Property</a>
                        <ul class="dropdown-menu">
                            <li><a href="single-property-1.html">Single Property 1</a></li>                                    
                            <li><a href="single-property-2.html">Single Property 2</a></li>                                    
                            <li><a href="single-property-3.html">Single Property 3</a></li>                                       
                        </ul>                                 
                    </li>
                    <li class="dropdown">
                        <a href="JavaScript:Void(0);">Agencies & Agents</a>
                        <ul class="dropdown-menu">
                            <li><a href="agents.html">Agents List</a></li>                                    
                            <li><a href="agent-page.html">Agent Page</a></li>                                    
                            <li><a href="agencies.html">Agencies List</a></li>                                    
                            <li><a href="agency-page.html">Agency Page</a></li>   
                        </ul>                                
                    </li>
                    <li class="dropdown">
                        <a href="JavaScript:Void(0);">My Account</a>
                        <ul class="dropdown-menu">
                            <li><a href="my-profile.html">My Profile</a></li>                                    
                            <li><a href="my-property.html">Property List</a></li>                                    
                            <li><a href="bookmark-list.html">Bookmarked Listings</a></li>                                    
                            <li><a href="change-password.html">Change Password</a></li>   
                        </ul>                                 
                    </li>
                    <li>
                        <a href="compare-property.html">Compare Property</a>                                
                    </li>
                    <li>
                        <a href="submit-property.html">Submit Property</a>                                
                    </li>
                </ul>
            </li>
            
            <li class="megamenu" data-width="500">
                <a href="#">Commerciaux</a>
                <div class="megamenu-content">
                    <div class="mg-menu">
                        <ul>
                            <li>
                                <a href="blog.html">
                                    <div class="mg-menu-items">
                                        <i class="ti-layout-grid2"></i>
                                        <h5>Blog Page<span>Checkout Our Articles</span></h5>
                                    </div>
                                </a>
                            </li>
                            
                            <li>
                                <a href="blog-detail.html">
                                    <div class="mg-menu-items">
                                        <i class="ti-layout"></i>
                                        <h5>Blog Detail<span>Detail Blog Page Design</span></h5>
                                    </div>
                                </a>
                            </li>
                            
                            <li>
                                <a href="pricing.html">
                                    <div class="mg-menu-items">
                                        <i class="ti-credit-card"></i>
                                        <h5>Pricing Page<span>Our Latest Offers & Package</span></h5>
                                    </div>
                                </a>
                            </li>
                            
                            <li>
                                <a href="contact.html">
                                    <div class="mg-menu-items">
                                        <i class="ti-location-pin"></i>
                                        <h5>Contact Us<span>Need Help? Get In Touch</span></h5>
                                    </div>
                                </a>
                            </li>
                            
                            <li>
                                <a href="component.html">
                                    <div class="mg-menu-items">
                                        <i class="ti-ruler-pencil"></i>
                                        <h5>Component<span>List of All Components</span></h5>
                                    </div>
                                </a>
                            </li>
                            
                            <li>
                                <a href="404.html">
                                    <div class="mg-menu-items">
                                        <i class="ti-face-sad"></i>
                                        <h5>Error Page<span>Error Page Design</span></h5>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>

           
            
        </ul>
            
    
        {% if request.user.is_authenticated %}
        <ul class="attributes">
            <li><a href="#" data-toggle="modal" data-target="#signup">Profile</a></li>
            <li class="login-attri theme-log"><a href="{% url 'logout' %}   " >logout</a></li>
        </ul>
        {% else %}

        <ul class="attributes">
            <!-- <li><a href="#" data-toggle="modal" data-target="#signup">Sign Up</a></li> -->
            <li class="login-attri theme-log"><a href="{% url 'login' %}">Log In</a></li>
        </ul>

        {% endif %}
        
    </nav>
</div>

<div class="clearfix"></div>